Config = {}

--- Cards Random duplicate means lower chances
Config.cards = { "bulbasaur", "ivysaur",  "charmander", "charmeleon",  "squirtle", "wartortle",  "caterpie", "metapod","caterpie", "metapod","caterpie", "metapod","caterpie", "metapod","caterpie", "metapod",
 "butterfree", "weedle", "kakuna", "weedle", "kakuna","weedle", "kakuna","weedle", "kakuna","weedle", "kakuna","beedrill", "pidgey","pidgey","pidgey","pidgey","pidgey", "rattata", "rattata", "rattata", "rattata",
"pidgeotto", "pidgeot", "rattata", "raticate", "spearow",  "spearow", "spearow", "spearow","spearow", "fearow", "ekans", "ekans", "ekans", "ekans", "ekans", "arbok", "pikachu", "raichu", "sandshrew", "sandslash", "nidoran", "nidorina", "nidoqueen", "nidorino", "nidoking", "clefairy",
"tentacool",  "tentacool",  "tentacool", "tentacool","tentacool","tentacool", "geodude","geodude","geodude","geodude","geodude","oddish","oddish","oddish","oddish","oddish","oddish", "diglett", "diglett", "diglett", "diglett",
"clefable", "vulpix", "ninetales", "jigglypuff", "wigglytuff", "zubat", "golbat", "oddish", "gloom", "vileplume", "paras", "parasect", "venonat", "venomoth", "diglett", "dugtrio", "meowth", "persian", "psyduck", 
"golduck", "mankey", "primeape", "growlithe", "arcanine", "poliwag", "poliwhirl", "poliwrath", "abra", "kadabra", "alakazam", "machop", "machoke", "machamp", "bellsprout", "weepinbell", "victreebel", "tentacool", 
"tentacruel", "geodude", "geodude", "geodude", "graveler", "golem", "ponyta", "rapidash", "slowpoke", "slowbro", "magnemite", "magneton", "farfetchd", "doduo", "dodrio", "seel", "dewgong", "grimer", "muk", "shellder", "cloyster", 
"gastly", "haunter", "gengar", "onix", "drowzee", "hypno", "krabby", "kingler", "voltorb", "electrode", "exeggcute", "exeggutor", "cubone", "marowak",  "lickitung", "koffing", "weezing", 
"rhyhorn", "rhydon", "chansey", "tangela", "kangaskhan", "horsea", "seadra", "goldeen", "seaking", "staryu", "starmie", "mrmime", "scyther", "jynx", "electabuzz", "magmar", "pinsir", "tauros", "magikarp", 
"gyarados", "lapras", "ditto", "eevee", "omanyte", "kabuto", "snorlax", "dratini", "dragonair"}

-- Rare Cards duplicate means lower chances
Config.cardsRare =  {
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "vaporeon",
    "jolteon",
    "flareon",
    "charizard",
    "blastoise",
    "venusaur",
    "dragonite",
    "togepi",
    "hitmonlee",
    "hitmonchan",
    "porygon",
    "omastar",
    "kabutops",
    "aerodactyl",
    "snorlax"
}

--- Badges duplicate means lower chances
Config.Badge =  {
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "volcanoBadge",
    "earthBadge",
    "trophyBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge",
    "boulderBadge",
    "cascadeBadge",
    "thunderBadge",
    "rainbowBadge",
    "soulBadge",
    "marshBadge"
}


Config.Weight = true -- if using Weight set  True if using Limit  set to false not tested on limit system try to adjust in  in server lua


-- notification types if both true/false then default notify will appear
Config.mythic = true
Config.tnotify = false
Config.tnotifyDuration = 1500 -- for tnotify only  2.5 seconds

---progressbars true if using flase if not select only 1
Config.progressbar = false --progbar normal
Config.UseProgressbar = true -- mythic progbar

---- waiting time to open card 10 secs
Config.OpenCard = 1500
Config.OpenCardRare = 1500
Config.OpenCardBadge = 1500


----Message
Config.OpeningBadge = 'Opening Poke Badge!'
Config.OpeningRare = 'Opening Poke Badge!'
Config.OpeningCard = 'Opening Pokemon Booster Pack'

Config.OpeningBadgeError = 'Already Opening Poke Badge!'
Config.OpeningRareError = 'Already Opening Rare Pack!'
Config.OpeningCardError = 'Already Opening Booster Pack!.'

Config.CannotCarry = 'Cannot Carry Anymore!'



